README.md
demo/README.md

* Small DX contribution to README.md
Help point out availability of local demo, and now to run it
* Update demo README.md
Added link to create-meeting-token API method

Small DX contributions to READMEs

---

package.json

This adds the `supportedBrowser().supportsScreenShare` check

Bump version to 0.9.986

---

package.json
src/module.js

Companion to https://github.com/daily-co/pluot-core/pull/1403/

load call-machine-object-nosfu-bundle for Edge

---

package.json
src/module.js

One more fix to this, after testing with Edgium.

fix sfu bundle browser check to properly handle Edgium

---

package.json
src/module.js
src/shared-with-pluot-core/CommonIncludes.js
src/shared-with-pluot-core/Util.js
src/shared-with-pluot-core/selectors.js

Companion to PR: https://github.com/daily-co/pluot-core/pull/1412

beta implementation of track subscriptions

---

src/call-object-loaders/CallObjectLoaderReactNative.js
src/call-object-loaders/CallObjectLoaderWeb.js
src/module.js
src/shared-with-pluot-core/script-message-channels/WebMessageChannel.js

companion to: https://github.com/daily-co/pluot-core/pull/1429

finish implementing callFrameId

---

src/module.js
wip-index.d.ts

NOTE: review https://github.com/daily-co/daily-js/pull/54 first, as this is dependent on it

Enable various methods for RN

---

package.json
src/module.js
src/shared-with-pluot-core/CommonIncludes.js
src/shared-with-pluot-core/script-message-channels/WebMessageChannel.js

Companion to: https://github.com/daily-co/pluot-core/pull/1399

live streaming

---

index.d.ts
package.json

Enable TypeScript type declarations file

---

index.d.ts

https://github.com/daily-co/daily-js/pull/69
https://github.com/daily-co/pluot-core/pull/1516

Set subscribed tracks types

---

index.d.ts
src/module.js

added "pl" to two files for Polish

added "pl" as a valid language

---

package.json

If there's any final sanity-checking needed, we could discuss it and record any results here.

Bump version to 0.9.992

---

index.d.ts

Minor tweaks applied on top of @hueter's contributions, originally in https://github.com/daily-co/daily-js/pull/81

Typescript declaration enhancements

---

index.d.ts

Hello!
My team has been using the TypeScript type declarations file since it's been included (see #52 ) and I've made some suggestions in this PR for improving the type defs.
Goals were:
- remove the instances of `any` and `object` where applicable
- type the events for the event handlers
- get tighter type definitions for built-ins (like the `MouseEvent` or `CSSStyleDeclaration`)
Feel free to discard as much as you want, or cherry-pick this as desired.
I based the event typings on the [reference docs](https://docs.daily.co/reference#events).
Hope this is useful! Happy to make requested changes or chat about things. 👍 
Update:
Sorry I force-pushed a few updates to this since I had some "a-ha" moments after I walked away from it of course 😅

Typescript type declaration enhancements

---

index.d.ts

Kudos to @dbanisimov for finding these mistakes!

Type declaration fixes

---

src/module.js

clear participants list when entering into error state

---

src/module.js

This change causes all meeting state transitions to funnel through a single state-update method, in order for state transitions to control whether we're asking the device to stay awake. "Staying awake" in this context means preventing the screen from dimming and eventually locking.
Fixes ENG-221.
Fixes ENG-220.
Here are the changes that enable this PR: https://github.com/daily-co/pluot-core/pull/1808

Ask the device to stay awake throughout the entire call lifecycle

---

index.d.ts
src/module.js

This is part of a synchronized 3-repo change described in https://github.com/daily-co/pluot-core/pull/1833.

React Native automatic audio configuration based on mode (video or voice call)

---

src/module.js

Fortunately, this only affects React Native

Remove a couple of accidentally-committed debug logs

---

src/module.js

See https://github.com/daily-co/pluot-core/pull/1889

Android background execution

---

index.d.ts

adding six new languages to match changes to core code

add six new languages

---

package-lock.json
package.json
src/module.js
webpack.config.js

See https://github.com/daily-co/pluot-core/pull/1936

Auto-muting in React Native

---

package-lock.json
package.json

@kwindla, @vipyne, just tagging you as an FYI. Will go ahead and merge since this is just part of the chain of version bumps to publish another version of `react-native-daily-js`.

0.9.993-beta.5

---

src/module.js

Add keys for six new languages

added new language keys

---

src/module.js

Reduces bundle size substantially!

import individual lodash functions

---

index.d.ts

Tested that autocompletion works correctly in VS Code, and validated behavior of all newly-typed functionality using the React demo.
Related PR: https://github.com/daily-co/pluot-core/pull/2361

TS declaration improvements

---

index.d.ts
src/Participant.js
src/module.js

Follow-up PR after this one is merged and `daily-js` is published: https://github.com/daily-co/pluot-core/pull/2379

ENG-803 Add MediaStreamTracks themselves to new participant.tracks object
