daily-co/daily-js

- src/CommonIncludes.js
- src/module.js
See the [Notion task](https://www.notion.so/dailyco/Make-Active-Speaker-Mode-controllable-via-the-JavaScript-API-efe8382a7b454e3db67cceee7217dc06) for context.
https://github.com/kwindla/pluot-core/pull/1357
> Active speaker mode control

- package.json
In preparation for deploying version of `daily-js` that provides programmatic control over active speaker mode.
Depends on latest `pluot-core` being deployed first.
> Bump version to 0.9.985

- package-lock.json
- package.json
- rollup.config.js
- src/module.js
- webpack.config.js
In production only, use the CDN to fetch `call-machine-object-bundle.js`. In other environments, use the relative path to deliver whatever is local (i.e. from the dev server running on your machine).
This requires pushing the build-time `NODE_ENV` env var down so we can access it at runtime in  `module.js`. Webpack's `DefinePlugin` handles this nicely for us so the code remains intuitive when the check occurs.
Matching PR in `pluot-core` to handle the other places we pull down call-machine: https://github.com/kwindla/pluot-core/pull/1373
Project card in Notion: https://www.notion.so/dailyco/Get-thee-to-a-CDN-call-machine-bundle-js-5645f07aeed34bdbaa5ef734c160ab2d
> Use CDN to fetch call-machine-object in prod

- src/CommonIncludes.js
- src/module.js
Add a new 'recording-data' event to allow handling of recording byte stream in javascript.
More information here in companion pluot-core pr: https://github.com/daily-co/pluot-core/pull/1387
> add API event for recording data

- src/module.js
Companion to https://github.com/daily-co/pluot-core/pull/1390
```
callObject.startScreenShare({ mediaStream: stream })
```
> add { mediaStream } option to startScreenShare()

- package.json
- src/utils.js
It's useful to have staging servers load `call-machine-object-bundle.js` from the origin server. This patch extends the cdn work that @sangelone did to also test whether the current meeting url is not a production meeting url. If it's not, we load the bundle from the origin server rather than the cdn.
> fix always loading bundle from cdn

- package.json
With this change `npm audit --production` passes.
> move rollup-plugin-terser to devDependencies

- src/module.js
Add the `display-capture` feature policy to the call iframe. Safari recently started enforcing this for screen sharing.
> display-capture permission on iframe

- src/module.js
- wip-index.d.ts
For each method in our API:
* Added a rough type declaration in `wip-index.d.ts`
* Honed it using our own documentation (if available) and Tandem's type declaration (if available)
* Further adjusted it based on careful inspection of our code
* Tested the declaration in VS Code by tweaking the React demo app to invoke the method in question (yup, VS Code lets you test TypeScript type checking in regular js files!)
* Ran the React demo app with the tweaks to verify that all the inputs and outputs were accurately captured by the declaration
Doesn't yet update `package.json` to publish the TypeScript file.
Also, I'm not sure yet whether it's good practice to embed all the types under the `DailyIframe` namespace. I wanted to first get all the types right in one PR—refactoring later should be …
> Complete TypeScript type declaration coverage of the `daily-js` API

- wip-index.d.ts
https://github.com/daily-co/pluot-core/pull/1466
Unfortunately we seem to need a bit of a complicated TypeScript setup to meet the following constraints:
- The `daily-js` package is meant for usage in the browser. As part of its type declarations, it should reference browser versions of WebRTC primitives (like `MediaStreamTrack`).
- The `react-native-daily-js` package is meant for usage in React Native, with the aid of the `react-native-webrtc` library. As part of its type declarations, it should reference `react-native-webrtc` versions of WebRTC primitives.
To do this, the `react-native-daily-js` package must:
- Override the types provided by `daily-js` during its compilation step.
- Expose those overridden types rather than `daily-js`'s original types when consumed by another project. …
> Make type declarations truly work for both RN and browser environments, and refactor them for snazziness

- src/call-object-loaders/CallObjectLoader.js
- src/call-object-loaders/CallObjectLoaderReactNative.js
- src/call-object-loaders/CallObjectLoaderWeb.js
- src/module.js
This PR does two things related to call object bundle loading:
- Introduces more graceful error handling when the call object bundle fails to load...
- ...by rejecting `load()` or `startCamera()` promises
- ...by entering the `error` meeting state
- ...by emitting the `error` event
- Introduces retry logic to call object bundle loading
This PR does *not* yet do the following, which I think will be valuable:
- Add call object bundle caching, to avoid loads entirely in some circumstances
- Properly handle calls to `load()` (and maybe other methods) while a load is still pending. This was a potential problem before this PR, and still is.
Design choice: rather than doing some refactoring to share retry logic between RN and web, I've decided to just keep them separate for now since I can …
> More robust call object bundle loading

- src/CallObjectLoader.js
https://github.com/daily-co/pluot-core/pull/1508
In React Native on iOS, I noticed that our `call-machine-object-bundle.js` wasn't ever being cached by the standard HTTP cache used by the `fetch` machinery. This meant that each time you `join()`ed a new call—between calls to `destroy()`—you'd have to first re-download the bundle.
I tracked the problem down to the fact that, since our bundle is pretty big (~3.6mb), the default iOS `URLCache` (the one used by React Native) simply opts not to cache it. Increasing the default `URLCache` size or instructing React Native to use another `URLCache` *would* resolve this problem, but React Native doesn't expose the necessary levers to do either of those things.
So here I've implemented as barebones a custom HTTP cache as I felt was reasonable, for …
> [React Native] Call object bundle caching on iOS

- index.d.ts
- package.json
Whoops! Accidentally merged this exact change into the old default branch, `master`. Redoing it into `main`.
> Enable TypeScript type declarations file

- src/module.js
This fixes an issue where calling `addFakeParticipant` on a call object results in access of undefined. addFakeParticipant still doesn't quite work as expected, but at least now a black box for the participant appears and no errors are admitted.
> check the whole path to rtcType.

- index.d.ts
- src/module.js
* Enables both `geo()` and `room()` methods in React Native
* Updates `room()` to return a `roomUrlPendingJoin` while we haven't successfully joined a room
> Some API additions

- src/module.js
Remove the arguments check that disallowed local video track subscription. It's not possible to subscribe to your own tracks. This has no effect in call object mode. In the prebuilt UI, if the local video cam track is subscribed to, then the local video will be displayed in the large main video panel, in addition to the normal lower left thumbnail.
```
callObject.updateParticipant('local', {
setSubscribedTracks: { video: true },
});
```
> allow setSubscribedTracks for local participant

- src/module.js
Fixes for:
- `join()` resulting in an immediate meeting error resulted in `meetingState()` not being equal to `'error'`
- when `meetingState()` was equal to `'error'`, the Promise returned by a call to `join()` never fulfilled.
> fixes to join()

- src/module.js
Because event handlers are called synchronously by the EventEmitter library we use, we swallow uncaught exceptions in event handler code, here. This patch adds the Error to our `console.log` to make it easier to track down exceptions in event handlers.
> added error message output to emit catch block

- package.json
Changes since 0.9.993-beta.3 have all been RN-related
> Bump version to 0.9.993-beta.4

- src/module.js
By default, `react-native-daily-js` does a few things automatically that fall under the umbrella of "automatic device management":
1. Picking an audio device automatically based on what devices are available and what the customer has specified as the "in-call audio mode" (defaulting to "video" but changeable to "voice" with the `setNativeInCallAudioMode()` method)
2. Muting or unmuting the mic based on whether app has audio focus (Android only)
3. Muting or unmuting the camera based on whether the app is in the background
There are at least some customer use-cases where overriding these behaviors might be desirable:
* Controlling audio route selection in native code (which would require bypassing 1)
* Using a framework like ConnectionService on Android to help you determine audio focus …
> Provide a way to bypass React Native default

- index.d.ts
- rollup.config.js
- src/module.js
- webpack.config.js
> Include daily-js version in pluot-core Sentry errors

- index.d.ts
- src/module.js
- src/shared-with-pluot-core/CommonIncludes.js
There are 2 PRs for this feature (`pluot-core` and `daily-js`). https://github.com/daily-co/pluot-core/pull/2326
Changes:
- add method `showParticipantsBar` to DailtyIframe, which accepts a boolean value (default `true`). I changed the phrase to be "participants bar" instead of "thumbnail" or "avatar" bar after chatting with Steve and Phil. This is the phrase we'll be using in the rewrite to be more consistent with our docs.
- add method `showLocalVideo` to DailtyIframe, which accepts a boolean value (default `true`).
> ENG-729 Add option to hide avatar bar/local video in calls

- index.d.ts
I'm guessing you don't want me to have to enter definitions for all 390 css properties. :)
So this should be `Partial<CSSStyleDeclaration>`
> Updating CSS style interface to not require all properties

- README.md
Excluding these instructions for using the main branch of daily-js since `main` won't work as is right now. Open to suggestions if anyone would prefer a rephrasing, though.
Btw, I tried running `npm run build` from within `node_modules/@daily-co/daily-js` and I get webpack errors, so that's why I lean towards removing vs. making the instructions more specific.
> ENG-823 Remove main branch instructions from README
